### ISSUE TITLE
mautic_url can target any URL

### ISSUE THREAD

**Issue by semisight** [leoschuler/gtag-mautic-event#1]
We strongly discourage tags using the "any" permission for `injectScript`/`sendPixel` because it means users can't trust this tag to be well scoped to trusted domains.

Is there a list of domains that we can restrict this to? If so, can you add that to the tag permissions?

https://github.com/leoschuler/gtag-mautic-event/blob/6277b92de4a4ed00548fe3dc81629b521c595b91/template.tpl#L127

**Comment by leoschuler** [comment]
unfortunately no, Mautic (https://www.mautic.org/) is a open source marketing automation tool (the biggest one). 
Like wordpress, you install it in your own domain, so every person using this tag will point to their own installation. 
in the code's defense: the user of this tag needs to specify the domain he wants, so typing the name of the domain is a way to say the user is trusting that domain.

other than that the inclusion of the pixel follows the specification of the mautic documentation: 
https://docs.mautic.org/en/contacts/manage-contacts/contact-monitoring#tracking-pixel

**Comment by leoschuler** [comment]
what I could do is to include a help/hint text for the mautic_url field explaining to the user he should only type a domain he trust, is that help?

**Comment by semisight** [comment]
That would be ideal; given that we can't scope this (by design), I've merged the template into gallery.
